### ISSUE TITLE
Issue in .net6.0 about OnBeforeVistaDialog

### ISSUE THREAD

**Issue by ahdung** [ptrsuder/IETU.Winforms#1]
Seems there is no 'OnBeforeVistaDialog' in .net6.0. Please fix.
https://github.com/ptrsuder/IETU.Winforms/blob/e94a03f6eda2ee66b41ab87a594bfa4de1e4f094/FolderSelectDialog/FolderSelectDialog.cs#L92

**Comment by ptrsuder** [comment]
This project is long abandoned and discarded.
